In [1]:
import torch
print(torch.__version__)

2.6.0


In [4]:
scalar = torch.tensor(2042)
scalar

tensor(2042)

In [6]:
type(scalar)

torch.Tensor

In [7]:
scalar.item()

2042

In [9]:
scalar.ndim

0

In [11]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [14]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 3])

In [18]:
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
random = torch.rand(3, 4)
print(f"Shape : {random.shape}")
print(f"DataType : {random.dtype}")
print(f"Device : {random.device}")

Shape : torch.Size([3, 4])
DataType : torch.float32
Device : cpu


In [21]:
op_tensor = torch.tensor([1,2,3])
op_tensor + 10

tensor([11, 12, 13])

In [22]:
op_tensor

tensor([1, 2, 3])

In [ ]:
op_tensor = op_tensor + 10
op_tensor

tensor([11, 12, 13])

In [31]:
op_tensor = torch.tensor([1,2,3])
op_tensor = op_tensor.add(10)
op_tensor

tensor([11, 12, 13])

In [ ]:
op_tensor = torch.tensor([1,2,3])
op_tensor = op_tensor.mul(2)
op_tensor

tensor([2, 4, 6])

In [34]:
op_tensor = torch.tensor([4,5,6])
op_tensor = op_tensor.sub(2)
op_tensor

tensor([2, 3, 4])

In [35]:
op_tensor = torch.tensor([4,6,8])
op_tensor = op_tensor.div(2)
op_tensor

tensor([2., 3., 4.])

In [45]:
mat_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(mat_tensor)

mat_tensor = mat_tensor.transpose(0, 1) # 0번 축 (row) 과 1번 축 (column) 을 바꿈
mat_tensor


tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [47]:
mat_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(mat_tensor.T)
print(mat_tensor)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [49]:
A = torch.tensor([[1,2],[3,4], [5,6]], dtype=torch.float32)
B = torch.tensor([[7,10],[8,11], [9,12]],dtype=torch.float32)

In [50]:
torch.matmul(A,B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
torch.matmul(A, B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])