In [1]:
import torch
print(torch.__version__)

2.6.0


In [4]:
scalar = torch.tensor(2042)
scalar

tensor(2042)

In [6]:
type(scalar)

torch.Tensor

In [7]:
scalar.item()

2042

In [9]:
scalar.ndim

0

In [11]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [14]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 3])

In [18]:
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
random = torch.rand(3, 4)
print(f"Shape : {random.shape}")
print(f"DataType : {random.dtype}")
print(f"Device : {random.device}")

Shape : torch.Size([3, 4])
DataType : torch.float32
Device : cpu


In [21]:
op_tensor = torch.tensor([1,2,3])
op_tensor + 10

tensor([11, 12, 13])

In [22]:
op_tensor

tensor([1, 2, 3])

In [ ]:
op_tensor = op_tensor + 10
op_tensor

tensor([11, 12, 13])